import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import SideBar from '@/components/SideBar';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <Header />
          <div className="flex flex-1 overflow-hidden">
            <SideBar />
            <main className="flex flex-1 flex-col overflow-y-auto p-4 bg-gray-100">
              <div className="flex-1">{children}</div>
              <div className="h-16"></div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
